apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - elastic-monitoring.yaml
  - namespace.yaml
  - nginx-ingress.yaml
  - postgres.yaml
  - redis.yaml
  - vault.yaml