apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress
  - certificates
  - vault
  - monitoring  
  - database
  - mesh
  - namespace.yaml
patchesStrategicMerge:
  - private-overlays.yaml